### ISSUE TITLE
Add Possibility to deactivate signup

### ISSUE THREAD

**Issue by alexohneander** [torrust/torrust-index#430]
There are situations where operators want to have the tracker/index public but where only selected users can upload things. 
For this it would be great to deactivate the SignUp and only add new users on Invite. 
What do you think or does this option already exist?

**Comment by josecelano** [comment]
> There are situations where operators want to have the tracker/index public but where only selected users can upload things. For this, it would be great to deactivate the SignUp and only add new users on Invite. What do you think or does this option already exist?

Hi, @alexohneander yes, that is something we have discussed many times:

- https://github.com/torrust/torrust-index-gui/discussions/91
- https://github.com/torrust/torrust-index-gui/discussions/285
- https://github.com/torrust/torrust-index/discussions/307
- https://github.com/torrust/torrust-index/discussions/306

I think this is one of the must-have features together with a [full-private mode](https://github.com/torrust/torrust-index/discussions/431). I have a list of them but we have not shared our priorities yet, even between the most active contributors. I think it would be a good idea to get feedback from the community about what are their priorities. We planned to do it after publishing an official roadmap. Maybe the best way to start collecting feedback is by opening a discussion in the "feature request" category and letting people up-vote it.

We have been postponing the roadmap because we are focused on the next big release [3.0.0](https://github.com/torrust/torrust-index/discussions/93). We are not including many new features from the end-user perspective (only small UX/UI improvements).

@cgbosse is collecting and organizing all the current open issues in all repos. We want to organize them in milestones. That's a big effort and we wanted to do it after releasing version 3.0.0.

cc @da2ce7

**Comment by josecelano** [comment]
Hi, @alexohneander; this was implemented a couple of months ago. If you remove the `
[registration]` section from the configuration, it will be disabled. Sorry for the delay.

Relates to: https://github.com/torrust/torrust-index-gui/issues/635
