### ISSUE TITLE
Error notification can be optimized

### ISSUE THREAD

**Issue by BelieveInBunny** [torrust/torrust-index#46]
![image](https://user-images.githubusercontent.com/50994966/168449310-f0621907-bdbc-4edb-a5af-d7315f8f2d77.png)

Error notification can be optimized to make it look better for some errors

**Comment by cgbosse** [comment]
Hi @BelieveInBunny .
Thank you for your suggestion we have taken note of the issue and added it to our idea backlog for future development.

Also, stay tuned since we are going to be posting our roadmap with new issues during the coming weeks and we may need your input and help.

Thank you very much.
